name: material_file_icon
description: A widget that displays a material file icon based on the file name.
version: 0.4.0
homepage: https://www.branvier.com
repository: https://github.com/arthurbcd/material_file_icon
topics:
 - material
 - file 
 - icon
 - icons

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cross_file: '>=0.3.3 <1.0.0'
  flutter:
    sdk: flutter
  flutter_svg: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/icons/